### ISSUE TITLE
Failed to build Side testnet image

### ISSUE THREAD

**Issue by hakuno2000** [strangelove-ventures/heighliner#256]
I tried to add these configs to chains.yaml

```
# Side testnet
- name: sidetestnet
  github-organization: sideprotocol
  github-repo: side
  dockerfile: cosmos
  build-env:
    - GO_VERSION=go1.22.0
  build-target: make build
  binaries:
    - build/sided
```

then run `heighliner build --chain sidetestnet --git-ref v0.9.0` and failed at this step

```
go build -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=sidechain -X github.com/cosmos/cosmos-sdk/version.AppName=sided -X github.com/cosmos/cosmos-sdk/version.Version=v0.9.0 -X github.com/cosmos/cosmos-sdk/version.Commit=f8f3845abd73d6307223f3a6fd5b340990595fce -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo ledger," -X github.com/cometbft/cometbft/version.TMCoreSemVer=v0.37.4 -w -s -linkmode external -extldflags "-static"' -trimpath -o /go/src/github.com/sideprotocol/side/build/ ./...
```

This is the log after that

```
# github.com/sideprotocol/side/cmd/sided
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lwasmvm.x86_64: No such file or directory
collect2: error: ld returned 1 exit status

make: *** [Makefile:127: build] Error 1
error building docker image for sidetestnet from ref: v0.9.0 - The command '/bin/sh -c set -eux;    export ARCH=$(uname -m);    if [ ! -z "${WASMVM_VERSION}" ]; then      WASMVM_REPO=$(echo $WASMVM_VERSION | awk '{print $1}');      WASMVM_VERS=$(echo $WASMVM_VERSION | awk '{print $2}');      wget -O /lib/libwasmvm_muslc.a https://${WASMVM_REPO}/releases/download/${WASMVM_VERS}/libwasmvm_muslc.$(uname -m).a;    fi;    export CGO_ENABLED=1 LDFLAGS='-linkmode external -extldflags "-static"';    if [ ! -z "$PRE_BUILD" ]; then sh -c "${PRE_BUILD}"; fi;    if [ ! -z "$BUILD_TARGET" ]; then      if [ ! -z "$BUILD_ENV" ]; then export ${BUILD_ENV}; fi;      if [ ! -z "$BUILD_TAGS" ]; then export "${BUILD_TAGS}"; fi;      if [ ! -z "$BUILD_DIR" ]; then cd "${BUILD_DIR}"; fi;      sh -c "${BUILD_TARGET}";    fi' returned a non-zero code: 2

panic: Some images failed to build

goroutine 1 [running]:
github.com/strangelove-ventures/heighliner/builder.(*HeighlinerBuilder).BuildImages(0xc00017a000)
        /root/heighliner/builder/builder.go:558 +0x109
github.com/strangelove-ventures/heighliner/cmd.queueAndBuild({{0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0, {0xff54da, 0x23}, {0xfe5515, 0x17}, ...}, ...)
        /root/heighliner/cmd/queue.go:125 +0x897
github.com/strangelove-ventures/heighliner/cmd.BuildCmd.func1(0xc0001af000?, {0xfd19c9?, 0x4?, 0xfd19cd?})
        /root/heighliner/cmd/build.go:135 +0x29e
github.com/spf13/cobra.(*Command).execute(0xc00044a848, {0xc0000bc580, 0x4, 0x4})
        /root/.gvm/pkgsets/go1.22/global/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x684
github.com/spf13/cobra.(*Command).ExecuteC(0xc00044a588)
        /root/.gvm/pkgsets/go1.22/global/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
        /root/.gvm/pkgsets/go1.22/global/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/strangelove-ventures/heighliner/cmd.Execute({0x1860820?, 0x17f8cb8?, 0xc0000061c0?})
        /root/heighliner/cmd/root.go:32 +0xe5
main.main()
        /root/heighliner/main.go:13 +0x28
```

**Comment by ash-burnt** [comment]
Having the same issue

**Comment by agouin** [comment]
This appears to be resolved now, please re-open if that is not the case.
