### ISSUE TITLE
Failed to build image on Windows

### ISSUE THREAD

**Issue by spoo-bar** [strangelove-ventures/heighliner#287]
Version: v1.6.3
OS: Windows 11 Pro 23H2 22631.4169
Docker version: 27.2.0 

Attempting to build an image with Heighliner fails with a panic
```powershell
PS C:\code\spoo-bar\heighliner> .\heighliner.exe build --chain gaia --git-ref v20.0.0
Loaded chains from C:\code\spoo-bar\heighliner\chains.yaml
Using local cosmos/native.Dockerfile
WasmVM from go.mod: repo: github.com/CosmWasm/wasmvm, version: v2.1.2
Go version from go.mod: 1.22.6, will build with version: 1.22.6 image: 1.22.6-alpine3.19
Building image from ref: v20.0.0, resulting docker image tags: +[gaia:v20.0.0]
error building docker image for gaia from ref: v20.0.0 - Error response from daemon: Cannot locate specified Dockerfile: heighliner2416018256\Dockerfile

panic: Some images failed to build

goroutine 1 [running]:
github.com/strangelove-ventures/heighliner/builder.(*HeighlinerBuilder).BuildImages(0xc0000f4000)
        C:/code/spoo-bar/heighliner/builder/builder.go:558 +0x232
github.com/strangelove-ventures/heighliner/cmd.queueAndBuild({{0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0, {0x2141adf, 0x23}, {0x21304aa, 0x17}, ...}, ...)
        C:/code/spoo-bar/heighliner/cmd/queue.go:125 +0x6c8
github.com/strangelove-ventures/heighliner/cmd.BuildCmd.func1(0xc0003fa600, {0xc000128b40, 0x0, 0x4})
        C:/code/spoo-bar/heighliner/cmd/build.go:135 +0x5c5
github.com/spf13/cobra.(*Command).execute(0xc0003fa600, {0xc000128b00, 0x4, 0x4})
        C:/Users/Spoorthi/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0xd0d
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003fa000)
        C:/Users/Spoorthi/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x9cf
github.com/spf13/cobra.(*Command).Execute(0xc0003fa000)
        C:/Users/Spoorthi/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x32
github.com/strangelove-ventures/heighliner/cmd.Execute({0x28ddc20, 0x8cbb, 0x8cbb})
        C:/code/spoo-bar/heighliner/cmd/root.go:32 +0x249
main.main()
        C:/code/spoo-bar/heighliner/main.go:13 +0x28
```
But the required file did exist on the local filesystem while this was running.

Probably tied to this? https://github.com/moby/moby/issues/41907

**Comment by agouin** [comment]
Does it work if you are not within the heighliner repo as the working directory? That will make it use the embedded Dockerfile.

Windows is highly untested.
